@startuml
digraph graph1 {

  node [style=filled];
  Paris -> Lyon [label="TGV"];

  Bordeaux -> "Geneve" [color=red];
  Paris -> Geneve [color=red];

  Paris -> Geneve [label="TGV"];
  Lyon -> "Clermont-Ferrand" [label="TER"];
  Lyon -> Marseille [label="TGV"];
  Lyon -> Paris [label="TGV"];
  Geneve -> Paris [label="TGV"];

}
@enduml
