@startuml

digraph memory {

  rankdir = LR;

  overlap = false;
  splines = true;

  subgraph cluster_0 {
    color=none;

    pile
    [
    shape = none
    label = <<table border="1" cellspacing="2">

    <tr><td colspan="2" border="1" bgcolor="gray">Pile</td></tr>
    <tr><td border="1" bgcolor="lightgray">Nom</td><td border="1" bgcolor="lightgray">Valeur</td></tr>

    'Zone mémoire du catalogue'
    <tr>
    <td colspan="2">
    <table>
    <tr>
    <td colspan="2" border="0">Catalogue</td>
    </tr>
    <tr>
    <td colspan="2" border="0">(Liste chaînée)</td>
    </tr>

    <tr>
    <td bgcolor="#d7d7d7" border="0">premierMaillon</td>
    <td bgcolor="#faf391" border="1" port="cpm">0x...</td>
    </tr>

    <tr>
    <td bgcolor="#d7d7d7" border="0">dernierMaillon</td>
    <td bgcolor="#f9dab2" border="1" port="cdm">0x...</td>
    </tr>

    <tr>
    <td bgcolor="#d7d7d7" border="0">taille</td>
    <td bgcolor="lightgray" border="1" port="cdm">3</td>
    </tr>

    </table>
    </td>
    </tr>
    'Fin de la zone mémoire du catalogue'

    </table>>
    ]

    tas
    [
    shape = none
    label = <<table border="1" cellspacing="2">

    <tr><td colspan="2" border="1" bgcolor="gray">Tas</td></tr>
    <tr><td border="1" bgcolor="lightgray">Nom</td><td border="1" bgcolor="lightgray">Valeur</td></tr>

    'Zone mémoire maillon catalogue m1'
    <tr>
    <td colspan="2">
    <table>
    <tr>
    <td port="m1" colspan="2" border="0">MaillonListeChaineeTrajets</td>
    </tr>
    <tr>
    <td colspan="2" border="0">(Entrée catalogue TS1)</td>
    </tr>

    <tr>
    <td bgcolor="#d7d7d7" border="0">trajet</td>
    <td bgcolor="#d3b2f9" border="1" port="m1t">0x...</td>
    </tr>

    <tr>
    <td bgcolor="#d7d7d7" border="0">maillonSuivant</td>
    <td bgcolor="#70a3d7" border="1" port="m1ms">0x...</td>
    </tr>

    </table>
    </td>
    </tr>
    'Fin de la zone mémoire maillon catalogue m1'

    'Zone mémoire maillon catalogue m2'
    <tr>
    <td colspan="2">
    <table>
    <tr>
    <td port="m2" colspan="2" border="0">MaillonListeChaineeTrajets</td>
    </tr>
    <tr>
    <td colspan="2" border="0">(Entrée catalogue TC2)</td>
    </tr>

    <tr>
    <td bgcolor="#d7d7d7" border="0">trajet</td>
    <td bgcolor="#d3b2f9" border="1" port="m2t">0x...</td>
    </tr>

    <tr>
    <td bgcolor="#d7d7d7" border="0">maillonSuivant</td>
    <td bgcolor="#70a3d7" border="1" port="m2ms">0x...</td>
    </tr>

    </table>
    </td>
    </tr>
    'Fin de la zone mémoire maillon catalogue m2'

    'Zone mémoire maillon catalogue m3'
    <tr>
    <td colspan="2">
    <table>
    <tr>
    <td port="m3" colspan="2" border="0">MaillonListeChaineeTrajets</td>
    </tr>
    <tr>
    <td colspan="2" border="0">(Entrée catalogue TS3)</td>
    </tr>

    <tr>
    <td bgcolor="#d7d7d7" border="0">trajet</td>
    <td bgcolor="#d3b2f9" border="1" port="m3t">0x...</td>
    </tr>

    <tr>
    <td bgcolor="#d7d7d7" border="0">maillonSuivant</td>
    <td bgcolor="#70a3d7" border="1" port="m3ms">nullptr</td>
    </tr>

    </table>
    </td>
    </tr>
    'Fin de la zone mémoire maillon catalogue m3'

    'Zone mémoire trajet simple TS1'
    <tr>
    <td colspan="2">
    <table>
    <tr>
    <td port="ts1" colspan="2" border="0">TrajetSimple</td>
    </tr>
    <tr>
    <td colspan="2" border="0">(TS1)</td>
    </tr>

    <tr>
    <td bgcolor="#d7d7d7" border="0">villeDepart</td>
    <td bgcolor="#b2f9ca" port="ts1villedep" border="1">0x...</td>
    </tr>

    <tr>
    <td bgcolor="#d7d7d7" border="0">villeArrivee</td>
    <td bgcolor="#b2f9ca" port="ts1villearr" border="1">0x...</td>
    </tr>

    <tr>
    <td bgcolor="#d7d7d7" border="0">typeTransport</td>
    <td bgcolor="#b2f9ca" port="ts1typetransp" border="1">0x...</td>
    </tr>

    </table>
    </td>
    </tr>
    'Fin de la zone mémoire TS1'

    'Zone mémoire trajet simple TS2-1'
    <tr>
    <td colspan="2">
    <table>
    <tr>
    <td port="ts2_1" colspan="2" border="0">TrajetSimple</td>
    </tr>
    <tr>
    <td colspan="2" border="0">(TS2-1)</td>
    </tr>

    <tr>
    <td bgcolor="#d7d7d7" border="0">villeDepart</td>
    <td bgcolor="#b2f9ca" port="ts2_1villedep" border="1">0x...</td>
    </tr>

    <tr>
    <td bgcolor="#d7d7d7" border="0">villeArrivee</td>
    <td bgcolor="#b2f9ca" port="ts2_1villearr" border="1">0x...</td>
    </tr>

    <tr>
    <td bgcolor="#d7d7d7" border="0">typeTransport</td>
    <td bgcolor="#b2f9ca" port="ts2_1typetransp" border="1">0x...</td>
    </tr>

    </table>
    </td>
    </tr>
    'Fin de la zone mémoire TS2-1'

    'Zone mémoire trajet simple TS2-2'
    <tr>
    <td colspan="2">
    <table>
    <tr>
    <td port="ts2_2" colspan="2" border="0">TrajetSimple</td>
    </tr>
    <tr>
    <td colspan="2" border="0">(TS2-2)</td>
    </tr>

    <tr>
    <td bgcolor="#d7d7d7" border="0">villeDepart</td>
    <td bgcolor="#b2f9ca" port="ts2_2villedep" border="1">0x...</td>
    </tr>

    <tr>
    <td bgcolor="#d7d7d7" border="0">villeArrivee</td>
    <td bgcolor="#b2f9ca" port="ts2_2villearr" border="1">0x...</td>
    </tr>

    <tr>
    <td bgcolor="#d7d7d7" border="0">typeTransport</td>
    <td bgcolor="#b2f9ca" port="ts2_2typetransp" border="1">0x...</td>
    </tr>

    </table>
    </td>
    </tr>
    'Fin de la zone mémoire TS2-2'

    'Zone mémoire trajet simple TS3'
    <tr>
    <td colspan="2">
    <table>
    <tr>
    <td port="ts3" colspan="2" border="0">TrajetSimple</td>
    </tr>
    <tr>
    <td colspan="2" border="0">(TS3)</td>
    </tr>

    <tr>
    <td bgcolor="#d7d7d7" border="0">villeDepart</td>
    <td bgcolor="#b2f9ca" port="ts3villedep" border="1">0x...</td>
    </tr>

    <tr>
    <td bgcolor="#d7d7d7" border="0">villeArrivee</td>
    <td bgcolor="#b2f9ca" port="ts3villearr" border="1">0x...</td>
    </tr>

    <tr>
    <td bgcolor="#d7d7d7" border="0">typeTransport</td>
    <td bgcolor="#b2f9ca" port="ts3typetransp" border="1">0x...</td>
    </tr>

    </table>
    </td>
    </tr>
    'Fin de la zone mémoire TS3'

    'Zone mémoire trajet simple TC2'
    <tr>
    <td colspan="2">
    <table>
    <tr>
    <td port="tc2" colspan="2" border="0">TrajetCompose</td>
    </tr>
    <tr>
    <td colspan="2" border="0">(TC2 - Liste chaînée)</td>
    </tr>

    <tr>
    <td bgcolor="#d7d7d7" border="0">premierMaillon</td>
    <td bgcolor="#faf391" port="tc2pm" border="1">0x...</td>
    </tr>

    <tr>
    <td bgcolor="#d7d7d7" border="0">dernierMaillon</td>
    <td bgcolor="#f9dab2" port="tc2dm" border="1">0x...</td>
    </tr>

    <tr>
    <td bgcolor="#d7d7d7" border="0">taille</td>
    <td bgcolor="lightgray" border="1" port="cdm">2</td>
    </tr>

    </table>
    </td>
    </tr>
    'Fin de la zone mémoire TC2'

    'Zone mémoire maillon trajet composé mtc1'
    <tr>
    <td colspan="2">
    <table>
    <tr>
    <td port="mtc2_1" colspan="2" border="0">MaillonListeChaineeTrajets</td>
    </tr>
    <tr>
    <td colspan="2" border="0">(Entrée TS2-1 TrajetCompose TC2)</td>
    </tr>

    <tr>
    <td bgcolor="#d7d7d7" border="0">trajet</td>
    <td bgcolor="#d3b2f9" border="1" port="mtc2_1t">0x...</td>
    </tr>

    <tr>
    <td bgcolor="#d7d7d7" border="0">maillonSuivant</td>
    <td bgcolor="#70a3d7" border="1" port="mtc2_1ms">0x...</td>
    </tr>

    </table>
    </td>
    </tr>
    'Fin de la zone mémoire maillon catalogue mtc1'

    'Zone mémoire maillon trajet composé mtc2'
    <tr>
    <td colspan="2">
    <table>
    <tr>
    <td port="mtc2_2" colspan="2" border="0">MaillonListeChaineeTrajets</td>
    </tr>
    <tr>
    <td colspan="2" border="0">(Entrée TS2-2 TrajetCompose TC2)</td>
    </tr>

    <tr>
    <td bgcolor="#d7d7d7" border="0">trajet</td>
    <td bgcolor="#d3b2f9" border="1" port="mtc2_2t">0x...</td>
    </tr>

    <tr>
    <td bgcolor="#d7d7d7" border="0">maillonSuivant</td>
    <td bgcolor="#70a3d7" border="1" port="mtc2_2ms">nullptr</td>
    </tr>

    </table>
    </td>
    </tr>
    'Fin de la zone mémoire maillon catalogue mtc2'

    </table>>
    ]

    pile:cpm:e -> tas:m1:w [penwidth=2 color="#c2be6f" fillcolor="#faf391"]
    pile:cdm:e -> tas:m3:w [penwidth=2 color="#b89f80" fillcolor="#f9dab2"]

    tas:tc2pm:e -> tas:mtc2_1:e [penwidth=2 color="#c2be6f" fillcolor="#faf391"]
    tas:tc2dm:e -> tas:mtc2_2:e [penwidth=2 color="#b89f80" fillcolor="#f9dab2"]

    tas:m1ms:e -> tas:m2:e [penwidth=2 color="#5d87b3" fillcolor="#70a3d7"]
    tas:m2ms:e -> tas:m3:e [penwidth=2 color="#5d87b3" fillcolor="#70a3d7"]
    tas:mtc2_1ms:e -> tas:mtc2_2:e [penwidth=2 color="#5d87b3" fillcolor="#70a3d7"]

    tas:m1t:e -> tas:ts1:e [penwidth=2 color="#86709e" fillcolor="#d3b2f9"]
    tas:m2t:e -> tas:tc2:e [penwidth=2 color="#86709e" fillcolor="#d3b2f9"]
    tas:m3t:e -> tas:ts3:e [penwidth=2 color="#86709e" fillcolor="#d3b2f9"]

    tas:mtc2_1t:e -> tas:ts2_1:e [penwidth=2 color="#86709e" fillcolor="#d3b2f9"]
    tas:mtc2_2t:e -> tas:ts2_2:e [penwidth=2 color="#86709e" fillcolor="#d3b2f9"]
  }

}

@enduml
